version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - d:/docker/my-wordpress/db_data:/var/lib/mysql 
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Maldit0.
       MYSQL_DATABASE: wp
       MYSQL_USER: wp
       MYSQL_PASSWORD: Maldit0.

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - d:/docker/my-wordpress/wp_data:/var/www/html
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wp
       WORDPRESS_DB_PASSWORD: Maldit0.
       WORDPRESS_DB_NAME: wp
   
   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports:
       - 8080:80
     environment:
       - PMA_HOST=db
     depends_on:
       - db
